### ISSUE TITLE
Failure in compiling the project of version  2.3.4.0

### ISSUE THREAD

**Issue by versemonger** [hortonworks/hive-release#1]
The command I used was 
mvn clean package  -DskipTests  -Phadoop-2,dist

The error message is shown below:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Hive
[INFO] Hive Shims Common
[INFO] Hive Shims 0.20S
[INFO] Hive Shims 0.23
[INFO] Hive Shims Scheduler
[INFO] Hive Shims
[INFO] Hive Common
[INFO] Hive Serde
[INFO] Hive Metastore
[INFO] Hive Ant Utilities
[INFO] Spark Remote Client
[INFO] Hive Query Language
[INFO] Hive Service
[INFO] Hive Accumulo Handler
[INFO] Hive JDBC
[INFO] Hive Beeline
[INFO] Hive CLI
[INFO] Hive Contrib
[INFO] Hive HBase Handler
[INFO] Hive HCatalog
[INFO] Hive HCatalog Core
[INFO] Hive HCatalog Pig Adapter
[INFO] Hive HCatalog Server Extensions
[INFO] Hive HCatalog Webhcat Java Client
[INFO] Hive HCatalog Webhcat
[INFO] Hive HCatalog Streaming
[INFO] Hive HWI
[INFO] Hive ODBC
[INFO] Hive Shims Aggregator
[INFO] Hive TestUtils
[INFO] Hive Packaging
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Hive 1.2.1.2.3.4.0-3485
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hive ---
[INFO] Deleting /Users/zl186017/Documents/HDP_Hive/hive-release/target
[INFO] Deleting /Users/zl186017/Documents/HDP_Hive/hive-release (includes = [datanucleus.log, derby.log], excludes = [])
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-no-snapshots) @ hive ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ hive ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (define-classpath) @ hive ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (setup-test-dirs) @ hive ---
[INFO] Executing tasks

main:
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/target/tmp
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/target/warehouse
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/target/tmp/conf
     [copy] Copying 11 files to /Users/zl186017/Documents/HDP_Hive/hive-release/target/tmp/conf
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-site-plugin:3.3:attach-descriptor (attach-descriptor) @ hive ---
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Hive Shims Common 1.2.1.2.3.4.0-3485
[INFO] ------------------------------------------------------------------------
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/zookeeper/zookeeper/3.4.6.2.3.4.0-3485/zookeeper-3.4.6.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/zookeeper/zookeeper/3.4.6.2.3.4.0-3485/zookeeper-3.4.6.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.zookeeper:zookeeper:jar:3.4.6.2.3.4.0-3485 is missing, no dependency information available
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hive-shims-common ---
[INFO] Deleting /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/target
[INFO] Deleting /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common (includes = [datanucleus.log, derby.log], excludes = [])
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-no-snapshots) @ hive-shims-common ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ hive-shims-common ---
[WARNING] Missing POM for org.apache.zookeeper:zookeeper:jar:3.4.6.2.3.4.0-3485
[WARNING] Missing POM for org.apache.zookeeper:zookeeper:jar:3.4.6.2.3.4.0-3485
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hive-shims-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/src/main/resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (define-classpath) @ hive-shims-common ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hive-shims-common ---
[INFO] Compiling 29 source files to /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/target/classes
[WARNING] /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/src/main/java/org/apache/hadoop/fs/ProxyFileSystem.java: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/src/main/java/org/apache/hadoop/fs/ProxyFileSystem.java uses or overrides a deprecated API.
[WARNING] /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/src/main/java/org/apache/hadoop/fs/ProxyFileSystem.java: Recompile with -Xlint:deprecation for details.
[WARNING] /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/src/main/java/org/apache/hadoop/hive/shims/HadoopShimsSecure.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/src/main/java/org/apache/hadoop/hive/shims/HadoopShimsSecure.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hive-shims-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/src/test/resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (setup-test-dirs) @ hive-shims-common ---
[INFO] Executing tasks

main:
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/target/tmp
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/target/warehouse
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/target/tmp/conf
     [copy] Copying 11 files to /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/target/tmp/conf
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hive-shims-common ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ hive-shims-common ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ hive-shims-common ---
[INFO] Building jar: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/common/target/hive-shims-common-1.2.1.2.3.4.0-3485.jar
[INFO] 
[INFO] --- maven-site-plugin:3.3:attach-descriptor (attach-descriptor) @ hive-shims-common ---
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Hive Shims 0.20S 1.2.1.2.3.4.0-3485
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hive-shims-0.20S ---
[INFO] Deleting /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/target
[INFO] Deleting /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S (includes = [datanucleus.log, derby.log], excludes = [])
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-no-snapshots) @ hive-shims-0.20S ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ hive-shims-0.20S ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hive-shims-0.20S ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/src/main/resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (define-classpath) @ hive-shims-0.20S ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hive-shims-0.20S ---
[INFO] Compiling 3 source files to /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/target/classes
[WARNING] /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/src/main/java/org/apache/hadoop/hive/shims/Hadoop20SShims.java: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/src/main/java/org/apache/hadoop/hive/shims/Hadoop20SShims.java uses or overrides a deprecated API.
[WARNING] /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/src/main/java/org/apache/hadoop/hive/shims/Hadoop20SShims.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hive-shims-0.20S ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/src/test/resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (setup-test-dirs) @ hive-shims-0.20S ---
[INFO] Executing tasks

main:
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/target/tmp
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/target/warehouse
    [mkdir] Created dir: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/target/tmp/conf
     [copy] Copying 11 files to /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/target/tmp/conf
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hive-shims-0.20S ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ hive-shims-0.20S ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ hive-shims-0.20S ---
[INFO] Building jar: /Users/zl186017/Documents/HDP_Hive/hive-release/shims/0.20S/target/hive-shims-0.20S-1.2.1.2.3.4.0-3485.jar
[INFO] 
[INFO] --- maven-site-plugin:3.3:attach-descriptor (attach-descriptor) @ hive-shims-0.20S ---
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Hive Shims 0.23 1.2.1.2.3.4.0-3485
[INFO] ------------------------------------------------------------------------
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-common/2.7.1.2.3.4.0-3485/hadoop-common-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-common/2.7.1.2.3.4.0-3485/hadoop-common-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-common:jar:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-hdfs/2.7.1.2.3.4.0-3485/hadoop-hdfs-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-hdfs/2.7.1.2.3.4.0-3485/hadoop-hdfs-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-hdfs:jar:2.7.1.2.3.4.0-3485 is missing, no dependency information available
[WARNING] The POM for org.apache.hadoop:hadoop-hdfs:jar:tests:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/2.7.1.2.3.4.0-3485/hadoop-mapreduce-client-core-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/2.7.1.2.3.4.0-3485/hadoop-mapreduce-client-core-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-mapreduce-client-jobclient/2.7.1.2.3.4.0-3485/hadoop-mapreduce-client-jobclient-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-jobclient/2.7.1.2.3.4.0-3485/hadoop-mapreduce-client-jobclient-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:tests:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/tez/tez-api/0.7.0.2.3.4.0-3485/tez-api-0.7.0.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/tez/tez-api/0.7.0.2.3.4.0-3485/tez-api-0.7.0.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.tez:tez-api:jar:0.7.0.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/tez/tez-runtime-library/0.7.0.2.3.4.0-3485/tez-runtime-library-0.7.0.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/tez/tez-runtime-library/0.7.0.2.3.4.0-3485/tez-runtime-library-0.7.0.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.tez:tez-runtime-library:jar:0.7.0.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/tez/tez-mapreduce/0.7.0.2.3.4.0-3485/tez-mapreduce-0.7.0.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/tez/tez-mapreduce/0.7.0.2.3.4.0-3485/tez-mapreduce-0.7.0.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.tez:tez-mapreduce:jar:0.7.0.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-api/2.7.1.2.3.4.0-3485/hadoop-yarn-api-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-api/2.7.1.2.3.4.0-3485/hadoop-yarn-api-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-api:jar:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-common/2.7.1.2.3.4.0-3485/hadoop-yarn-common-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-common/2.7.1.2.3.4.0-3485/hadoop-yarn-common-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-common:jar:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-client/2.7.1.2.3.4.0-3485/hadoop-yarn-client-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-client/2.7.1.2.3.4.0-3485/hadoop-yarn-client-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-client:jar:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-server-resourcemanager/2.7.1.2.3.4.0-3485/hadoop-yarn-server-resourcemanager-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-server-resourcemanager/2.7.1.2.3.4.0-3485/hadoop-yarn-server-resourcemanager-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-server-resourcemanager:jar:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/tez/tez-tests/0.7.0.2.3.4.0-3485/tez-tests-0.7.0.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/tez/tez-tests/0.7.0.2.3.4.0-3485/tez-tests-0.7.0.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.tez:tez-tests:jar:tests:0.7.0.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-server-tests/2.7.1.2.3.4.0-3485/hadoop-yarn-server-tests-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-server-tests/2.7.1.2.3.4.0-3485/hadoop-yarn-server-tests-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-distcp/2.7.1.2.3.4.0-3485/hadoop-distcp-2.7.1.2.3.4.0-3485.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-distcp/2.7.1.2.3.4.0-3485/hadoop-distcp-2.7.1.2.3.4.0-3485.pom
[WARNING] The POM for org.apache.hadoop:hadoop-distcp:jar:2.7.1.2.3.4.0-3485 is missing, no dependency information available
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-common/2.7.1.2.3.4.0-3485/hadoop-common-2.7.1.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-hdfs/2.7.1.2.3.4.0-3485/hadoop-hdfs-2.7.1.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-hdfs/2.7.1.2.3.4.0-3485/hadoop-hdfs-2.7.1.2.3.4.0-3485-tests.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/2.7.1.2.3.4.0-3485/hadoop-mapreduce-client-core-2.7.1.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-mapreduce-client-jobclient/2.7.1.2.3.4.0-3485/hadoop-mapreduce-client-jobclient-2.7.1.2.3.4.0-3485-tests.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/tez/tez-api/0.7.0.2.3.4.0-3485/tez-api-0.7.0.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/tez/tez-runtime-library/0.7.0.2.3.4.0-3485/tez-runtime-library-0.7.0.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/tez/tez-mapreduce/0.7.0.2.3.4.0-3485/tez-mapreduce-0.7.0.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-api/2.7.1.2.3.4.0-3485/hadoop-yarn-api-2.7.1.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-common/2.7.1.2.3.4.0-3485/hadoop-yarn-common-2.7.1.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-client/2.7.1.2.3.4.0-3485/hadoop-yarn-client-2.7.1.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-server-resourcemanager/2.7.1.2.3.4.0-3485/hadoop-yarn-server-resourcemanager-2.7.1.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/tez/tez-tests/0.7.0.2.3.4.0-3485/tez-tests-0.7.0.2.3.4.0-3485-tests.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-distcp/2.7.1.2.3.4.0-3485/hadoop-distcp-2.7.1.2.3.4.0-3485.jar
Downloading: http://www.datanucleus.org/downloads/maven2/org/apache/hadoop/hadoop-yarn-server-tests/2.7.1.2.3.4.0-3485/hadoop-yarn-server-tests-2.7.1.2.3.4.0-3485-tests.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-common/2.7.1.2.3.4.0-3485/hadoop-common-2.7.1.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-hdfs/2.7.1.2.3.4.0-3485/hadoop-hdfs-2.7.1.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-hdfs/2.7.1.2.3.4.0-3485/hadoop-hdfs-2.7.1.2.3.4.0-3485-tests.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/2.7.1.2.3.4.0-3485/hadoop-mapreduce-client-core-2.7.1.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-jobclient/2.7.1.2.3.4.0-3485/hadoop-mapreduce-client-jobclient-2.7.1.2.3.4.0-3485-tests.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/tez/tez-api/0.7.0.2.3.4.0-3485/tez-api-0.7.0.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/tez/tez-runtime-library/0.7.0.2.3.4.0-3485/tez-runtime-library-0.7.0.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/tez/tez-mapreduce/0.7.0.2.3.4.0-3485/tez-mapreduce-0.7.0.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-api/2.7.1.2.3.4.0-3485/hadoop-yarn-api-2.7.1.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-common/2.7.1.2.3.4.0-3485/hadoop-yarn-common-2.7.1.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-client/2.7.1.2.3.4.0-3485/hadoop-yarn-client-2.7.1.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-server-resourcemanager/2.7.1.2.3.4.0-3485/hadoop-yarn-server-resourcemanager-2.7.1.2.3.4.0-3485.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/tez/tez-tests/0.7.0.2.3.4.0-3485/tez-tests-0.7.0.2.3.4.0-3485-tests.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-server-tests/2.7.1.2.3.4.0-3485/hadoop-yarn-server-tests-2.7.1.2.3.4.0-3485-tests.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-distcp/2.7.1.2.3.4.0-3485/hadoop-distcp-2.7.1.2.3.4.0-3485.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Hive ............................................... SUCCESS [  1.441 s]
[INFO] Hive Shims Common .................................. SUCCESS [  4.486 s]
[INFO] Hive Shims 0.20S ................................... SUCCESS [  0.522 s]
[INFO] Hive Shims 0.23 .................................... FAILURE [ 12.174 s]
[INFO] Hive Shims Scheduler ............................... SKIPPED
[INFO] Hive Shims ......................................... SKIPPED
[INFO] Hive Common ........................................ SKIPPED
[INFO] Hive Serde ......................................... SKIPPED
[INFO] Hive Metastore ..................................... SKIPPED
[INFO] Hive Ant Utilities ................................. SKIPPED
[INFO] Spark Remote Client ................................ SKIPPED
[INFO] Hive Query Language ................................ SKIPPED
[INFO] Hive Service ....................................... SKIPPED
[INFO] Hive Accumulo Handler .............................. SKIPPED
[INFO] Hive JDBC .......................................... SKIPPED
[INFO] Hive Beeline ....................................... SKIPPED
[INFO] Hive CLI ........................................... SKIPPED
[INFO] Hive Contrib ....................................... SKIPPED
[INFO] Hive HBase Handler ................................. SKIPPED
[INFO] Hive HCatalog ...................................... SKIPPED
[INFO] Hive HCatalog Core ................................. SKIPPED
[INFO] Hive HCatalog Pig Adapter .......................... SKIPPED
[INFO] Hive HCatalog Server Extensions .................... SKIPPED
[INFO] Hive HCatalog Webhcat Java Client .................. SKIPPED
[INFO] Hive HCatalog Webhcat .............................. SKIPPED
[INFO] Hive HCatalog Streaming ............................ SKIPPED
[INFO] Hive HWI ........................................... SKIPPED
[INFO] Hive ODBC .......................................... SKIPPED
[INFO] Hive Shims Aggregator .............................. SKIPPED
[INFO] Hive TestUtils ..................................... SKIPPED
[INFO] Hive Packaging ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.016 s
[INFO] Finished at: 2016-06-24T10:21:14-07:00
[INFO] Final Memory: 43M/474M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hive-shims-0.23: Could not resolve dependencies for project org.apache.hive.shims:hive-shims-0.23:jar:1.2.1.2.3.4.0-3485: The following artifacts could not be resolved: org.apache.hadoop:hadoop-common:jar:2.7.1.2.3.4.0-3485, org.apache.hadoop:hadoop-hdfs:jar:2.7.1.2.3.4.0-3485, org.apache.hadoop:hadoop-hdfs:jar:tests:2.7.1.2.3.4.0-3485, org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.7.1.2.3.4.0-3485, org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:tests:2.7.1.2.3.4.0-3485, org.apache.tez:tez-api:jar:0.7.0.2.3.4.0-3485, org.apache.tez:tez-runtime-library:jar:0.7.0.2.3.4.0-3485, org.apache.tez:tez-mapreduce:jar:0.7.0.2.3.4.0-3485, org.apache.hadoop:hadoop-yarn-api:jar:2.7.1.2.3.4.0-3485, org.apache.hadoop:hadoop-yarn-common:jar:2.7.1.2.3.4.0-3485, org.apache.hadoop:hadoop-yarn-client:jar:2.7.1.2.3.4.0-3485, org.apache.hadoop:hadoop-yarn-server-resourcemanager:jar:2.7.1.2.3.4.0-3485, org.apache.tez:tez-tests:jar:tests:0.7.0.2.3.4.0-3485, org.apache.hadoop:hadoop-yarn-server-tests:jar:tests:2.7.1.2.3.4.0-3485, org.apache.hadoop:hadoop-distcp:jar:2.7.1.2.3.4.0-3485: Could not find artifact org.apache.hadoop:hadoop-common:jar:2.7.1.2.3.4.0-3485 in datanucleus (http://www.datanucleus.org/downloads/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by versemonger** [comment]
It is similar with version 2.3.4.7

**Comment by onlyforcloud** [comment]
@versemonger Hello, would you explain how to solve this problem? 
I just substitute null string for all .2.3.4.0-3485.

**Comment by versemonger** [comment]
@onlyforcloud Hi, Sorry but I have forgotten the dtailed solution and don't have time getting it back now, but the general idea is to fix package dependency problem in pom.xml file of the whole project.

**Comment by onlyforcloud** [comment]
@versemonger I've found http://repo.hortonworks.com/content/repositories/releases/ is the hdp repository.
